# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   password: <%= ENV['DATABASE_PASSWORD'] %>
#   url: <%= Rails.application.credentials.db[:url] %>
#   database: <%= Rails.application.credentials.db[:database] %>
#   username: <%= Rails.application.credentials.db[:username] %>
#   password: <%= Rails.application.credentials.db[:password] %>

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= Rails.application.credentials.db[:pro_username] %>
  password: <%= Rails.application.credentials.db[:pro_password] %>
  host: localhost

development:
  <<: *default
  database: onsen_development

test:
  <<: *default
  database: onsen_test

production:
  <<: *default
  database: onsen_production
  # username: <%= Rails.application.credentials.db[:pro_username] %>
  # password: <%= Rails.application.credentials.db[:pro_password] %>
